learn_in/api/urls.py
app_name = 'api'

urlpatterns = []

learn_in/learn_in/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from users.urls import authpatterns

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('auth/', include((authpatterns, 'users-app'), namespace='auth')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('users/', include('users.urls', namespace='users')),
]

learn_in/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetView
)
from django.urls import path, reverse_lazy

from .views import SignUp, StudentGroupDetailView, UserDetailView, UserListView

app_name = 'users-app'

authpatterns = [
    path(
        'signup/',
        SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='auth/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='auth/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'password-change/',
        PasswordChangeView.as_view(
            template_name='auth/password_change_form.html'
        ),
        name='password-change'
    ),
    path(
        'password-change/done/',
        PasswordChangeDoneView.as_view(
            template_name='auth/password_change_done.html'
        ),
        name='password-change-done'
    ),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='auth/password_reset_form.html',
            email_template_name='auth/password_reset_email.html',
            success_url=reverse_lazy('auth:password-reset-done')
        ),
        name='password-reset-form'
    ),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(
            template_name='auth/password_reset_done.html'
        ),
        name='password-reset-done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='auth/password_reset_confirm.html',
            success_url=reverse_lazy('auth:password-reset-complete')
        ),
        name='password-reset-confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='auth/password_reset_complete.html'
        ),
        name='password-reset-complete'
    ),
]

urlpatterns = [
    path(
        '',
        UserListView.as_view(),
        name='user-list'
    ),
    path(
        'user/<str:username>/',
        UserDetailView.as_view(),
        name='user-detail'
    ),
    path(
        'student-group/<slug:slug>/',
        StudentGroupDetailView.as_view(),
        name='student-group-detail'
    ),
]

learn_in/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    """Настроенная модель пользователя."""

    class Role(models.TextChoices):
        """Статус пользователя: преподаватель/студент."""
        TEACHER = 'teacher'
        STUDENT = 'student'

    role = models.CharField(
        max_length=7,
        choices=Role.choices,
        default=Role.STUDENT,
        verbose_name='роль'
    )
    bio = models.TextField(
        null=True,
        blank=True,
        verbose_name='описание'
    )

    class Meta:
        ordering = ('username',)

    def get_absolute_url(self):
        return reverse('users:user-detail', kwargs={'username': self.username})

    def __str__(self):
        return self.username


class Base(models.Model):
    """Базовый класс для задач, а также групп студентов и задач."""

    title = models.CharField(
        unique=True,
        max_length=250,
        verbose_name='название'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='слаг'
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='описание'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата создания'
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='дата обновления'
    )

    class Meta:
        abstract = True
        ordering = ('title',)

    def __str__(self):
        return self.title

learn_in/core/templates/includes/footer.html
<div class="fixed-bottom text-center py-4 bg-dark">
  <p style="color:grey">© {{ year }}, H-6 Design Group</p>  
</div> 

learn_in/core/templates/includes/header.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href={% url 'index' %}>
      <span style="color:blue">Learn</span><span style="color:grey">-in</span>
    </a>
    {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link
            {% if view_name  == 'tasks:task-list' %}active{% endif %}"
            href="{% url 'tasks:task-list' %}">
            Tasks
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link
            {% if view_name  == 'users:user-list' %}active{% endif %}"
            href="{% url 'users:user-list' %}">
            Users
          </a>
        </li>
        {% if user.is_authenticated %}
          <button class="navbar-toggler" type="button" 
            data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" 
            aria-controls="navbarNavDarkDropdown" aria-expanded="false" 
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" 
                  id="navbarDarkDropdownMenuLink" role="button" 
                  data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
                <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" 
                  aria-labelledby="navbarDarkDropdownMenuLink">
                  <li>
                    <a class="dropdown-item"
                      href="{{ user.get_absolute_url }}">
                      {{ user.username }}
                    </a>
                  </li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'auth:logout' %}">
                      Log-out
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light
              {% if view_name  == 'auth:login' %}active{% endif %}"
              href="{% url 'auth:login' %}">
              Log-in
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light
              {% if view_name  == 'auth:signup' %}active{% endif %}"
              href="{% url 'auth:signup' %}">
              Sign-up
            </a>
          </li>
        {% endif %}
      </ul>
    {% endwith %} 
  </div>
</nav>